### ISSUE TITLE
Provision AKS cluster with Managed Identity

### ISSUE THREAD

**Issue by syedhassaanahmed** [magicaks/magicaks#24]
AKS clusters can now be provisioned using [Managed Identity](https://docs.microsoft.com/en-us/azure/aks/use-managed-identity). This means there is no longer a need to create a Service Principal and specify it as part of [AKS provisioning](https://github.com/sachinkundu/akstf/blob/master/2-provision-aks/aks/aks.tf#L27). A system-assigned identity will be automatically created and tied to the cluster's lifecycle, making sure we don't run into Service Principal secret expiry issues. All subsequent AAD roles can then be assigned to the system-assigned identity.

**Comment by Lybecker** [comment]
Here is [an example](https://www.chriswoolum.dev/aks-with-managed-identity-and-terraform) of enabling managed identity with TF
