### ISSUE TITLE
Check validity of the README

### ISSUE THREAD

**Issue by sachinkundu** [magicaks/magicaks#31]
And make sure that steps are in logical order.

**Comment by christoferlof** [comment]
As I was reading through the README and following the instructions in there, I updated the provided Docker developer image with the required tools.
Hopefully this could speed up onboarding.
Please see #38

**Comment by christoferlof** [comment]
- [ ] test

**Comment by christoferlof** [comment]
closing this. We're pretty confident of the current state and issues. New items to be tracked as separate issues.
