### ISSUE TITLE
Improve the Developer Experience of checking out the project

### ISSUE THREAD

**Issue by sachinkundu** [magicaks/magicaks#33]
Reduce the number of steps to start using the project.

**Comment by christoferlof** [comment]
Epic for EFR1. Additional steps/items to be created. 

- [ ] Get shared variables from the user and create .tfvar files in each of the provisioning directories
- [ ] Get output from Terraform after running 1-preprovision and prepopulate .tfvar files with that output
- [ ] Add `az` commands to bash script and capture output and populate .tfvar files
- [ ] Automate creation of required Git repositories
- [ ] Avoid having to keep .tfstate in main
- [ ] Wait for resources to be created in step 3 (Related to Troubleshooting guide #60)
- [ ] Clean up resources that were provisioned
- [ ] Add steps to validate cluster and other resources after being provisioned

**Comment by christoferlof** [comment]
Above items created as separate issues now. Closing this issue as the milestone represents the goal that was expressed in this issue.
