### ISSUE TITLE
Add information in the setup.md about how to find the variables for the provision-aks and postprovision steps

### ISSUE THREAD

**Issue by TessFerrandez** [magicaks/magicaks#58]
The tf scripts use many variables and it can be a bit tricky to figure out where to find them, and the format. A table like the one for the .env file would help here

Also update the variables for 1-preprovision

**Comment by TessFerrandez** [comment]
And.. clean up the names for the variables so they are easier to understand

**Comment by sachinkundu** [comment]
can we add a ready made terraform.tfvars.tmpl with filled in fake values so that one knows what the values must look like.

**Comment by TessFerrandez** [comment]
yes
