### ISSUE TITLE
Avoid having to keep all .tfstate in main

### ISSUE THREAD

**Issue by christoferlof** [magicaks/magicaks#70]

**Comment by Lybecker** [comment]
The point is to simplify. MagicAKS has 3 Terraform files - all which has a section for where to store the tfstate configured in the backend configuration like so:

```terraform
terraform {
  backend "azurerm" {
    resource_group_name  = "dev"
    container_name = "tfstate"
    key = "magicaks-longlasting"
    storage_account_name = "anlybeckstorage"
  }
}
```

It is possible to use [partial config](https://www.terraform.io/docs/language/settings/backends/configuration.html#partial-configuration) and override the settings like `terraform init -backend-config=PATH`. 

Via `TF_CLI_ARGS_init` the argument will automatically be applied to `terraform init` commands as explained [here](https://github.com/hashicorp/terraform/pull/20428). 

Combining those to a separate config file and a variable like:
```bash
export TF_CLI_ARGS_init='-backend-config=<path to config file>'
```
