### ISSUE TITLE
Suggestion: Rename ARM_CLIENT_ID and ARM_CLIENT_SECRET

### ISSUE THREAD

**Issue by TessFerrandez** [magicaks/magicaks#85]
Rename the client ID, client secret and arm access key to something a bit more descriptive

```cmd
export ARM_SUBSCRIPTION_ID=
export ARM_TENANT_ID=
export ARM_CLIENT_ID=
export ARM_CLIENT_SECRET=
# Storage access key where the terraform state information is to be stored.
export ARM_ACCESS_KEY=
```

**Comment by sachinkundu** [comment]
Are these names not fixed and required as is by terrafrom resource provider for Azure https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#argument-reference??

**Comment by TessFerrandez** [comment]
thanks, did not know that - closing the issue
