### ISSUE TITLE
some variables are not available in the tfvars template for step 2

### ISSUE THREAD

**Issue by TessFerrandez** [magicaks/magicaks#90]
dns_prefix
log_analytics_workspace_location

**Comment by sachinkundu** [comment]
I think dns_prefix and log_analytics_workspace_location are no longer needed as where dns_prefix was being used now cluster_name is used and where log_analytics_workspace_location was used resource group location is used instead. If there are places still in the code saying dns_prefix then that should be fixed instead.

**Comment by TessFerrandez** [comment]
In the current version in master - it is still asking for this - perhaps just that the variables.tf file was not updated
